### ISSUE TITLE
Option "public: true" to replace resource "web"

### ISSUE THREAD

**Issue by jedahan** [buglabs/bugswarm-js#1]
The quickest setup for producing and consuming data is currently:
1. Signup on bugswarm.net / community.buglabs.net
2. Get an api key with your username/password
3. Use api key to create a swarm
4. Use api key to create a resource of type 'web'
5. Use api key to add that resource web to that swarm
6. Use library to join that swarm

To make this easier, I suggest the option 'public: true' to replace steps 4 and 5:
1. Signup on bugswarm.net / community.buglabs.net
2. Get an api key with your username/password
3. Use api key to create a swarm, with "public: true"
4. Use library to join that swarm

**Comment by aturley** [comment]
Are you still talking about automatically creating a resource if you try to join a swarm without specifying a resource ID? I'm assuming that's what you mean since that's what we talked about on Friday.

I'll articulate my objections here so that we have a paper trail, but they are the same things we discussed on Friday ...

I'm hesitant to do something like this because it has an impact on our pricing model and it differs enough from our existing mental model of BUGswarm that I believe it represents a large change that should only be undertaken with a full understanding of its impact on the rest of the system. If we can address these concerns then I will feel more comfortable moving forward with this plan.

If we create resources automatically and we charge on a per-resource basis then our system is set up to automatically increase customer cost. We should only add cost through explicit user action, not automatically. If we can categorically say that we will not charge on a per-resource basis then I will feel better on this count, but there's still a cost in time related to cleaning up these resources if the user decides not to use them.

Our current model is based on users explicitly creating resources, and I think we've made some design assumptions around that model. Some of those assumptions were implicit, so we will need to spend some time spelling them out before we move ahead with a plan that invalidates them. If we do not think this through then we risk creating a feature that feels at odds with the rest of the system, which will lead to a poor user experience, and I'm against creating in a poor user experience in one area just to marginally improve the user experience in another area. If we see understand the impact of this change on the whole system and decide that it is justified then we should move forward, but until then the status quo should remain in place.

I'm open to other thoughts.

**Comment by c4milo** [comment]
@aturley I believe Jonathan is not talking about creating and adding resources automagically under the hood. Public swarms are an existing feature and it came from the previous version of BUGswarm. The rules to allow users to join swarms are any of the following:
1. Swarm is public
2. Requester user is the swarm owner.
3. Requester user has a 'web' resource which was previously invited to the swarm by the swarm owner.

With the ongoing release, rule number 3 will apply now to any user resource.

**Comment by aturley** [comment]
To which resource in Jonathan's example does rule 3 apply? Because no resource was created at any point (that's what happened in the steps that were removed), so as far as I can tell we're talking about a user with no resources. Do you mean that we should create a resource beforehand and suggest that the user use that resource in the example? I seem to recall that being discussed briefly in one of the meetings. Jonathan, if that is the case, please add that to the issue's description. Otherwise, please help me understand what you're proposing.

**Comment by jedahan** [comment]
Per our discussion friday, this feature suggestion is bad. Will re-explore what I am trying to get at later.
