### ISSUE TITLE
Wrap REST api in javascript

### ISSUE THREAD

**Issue by jedahan** [buglabs/bugswarm-js#2]
I propose methods (create, list, update, destroy, add, etc...) that take the same json as the REST api.

This will make it easy to stay with the same language instead of relying on external tools (bugswarm-tools, curl, bug management UI).
## Create a swarm

```
SWARM.create({ "swarm": {
    "name": "My Swarm",
    "description": "My Swarm Description",
    "public": false
} })
```
## Destroy a resource

```
SWARM.destroy({ "resource": {
    "id": "my unique resource id",
    "name": "My resource",
    "machine_type": "pc",
    "description": "My Resource description",
    "position": {
                    "longitude": 0,
                    "latitude": 0
    }
}})
```
## Add a resource to a swarm

```
SWARM.add("$SWARM_ID", { "resource": {
     "user_id": "username",
     "resource": "My Resource id",
     "type": "consumer"
 }})
```

Not sure what the best mapping is from REST to the javascript api, but this is a start.

**Comment by c4milo** [comment]
I don't see any problem here, @aturley? Maybe we should wait till some customer ask for it?

**Comment by c4milo** [comment]
Sorry to be late to this party.

My first thought would be to wait until a customer needs it, but it looks like Jonathan needs it for the tutorial. 

Is this going to require backend work? I thought that was going to be necessary because you can't just call out to the ReSTful API from JavaScript in the browser due to cross-site scripting restrictions. If we can get around this then I'm fine with it.

**Comment by aturley** [comment]
Crap, that last comment was from me. Sorry @c4milo. I logged you out of the computer in CH.

**Comment by jedahan** [comment]
It is not necessary for the tutorial. I just pre-setup swarms for people to use in the tutorial.

**Comment by barberdt** [comment]
With connector/web UI on hold, I'm finding myself with some time. How difficult would this be to implement?
